### ISSUE TITLE
Aggregate dependency scopes

### ISSUE THREAD

**Issue by Gabriel-Darbord** [moosetechnology/MooseNexus#8]
The same dependency can exist in multiple scopes (this happens a lot with Gradle).
Instead of having to choose one when flattening, and also when adding it to each subproject's dependencies, only one dependency should exist with multiple scopes.

```yaml
dependencies:
  - group:   <dependencyGroup>
    name:    <dependencyName>
    version: <dependencyVersion>
    scopes:  <dependencyScopes>
    type:    <dependencyType>
```
